config/routes.rb
Rails.application.routes.draw do

  root "home#top"
  
  get "home/about" =>"home#about"
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update, :index] do
  	member do
  		get :following, :followers
  	end
  end
  resources :relationships, only:[:create,:destroy]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only:[:create,:destroy]
 end
 get '/search' => 'search#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :book_comments,dependent: :destroy
         has_many :following,foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
          has_many :followings, through: :following
          has_many :follower,foreign_key: "following_id",class_name: "Relationship", dependent: :destroy
          has_many :followers, through: :follower

         attachment :profile_image
         validates :name, presence: true,uniqueness: true ,length: {minimum: 2,maximum:20}
         validates :introduction,length:{maximum: 50}


         def favorited_by?(user)
         	favorites.where(user_id: user.id).exists?
         end

         def following?(other_user)
            following.find_by(following_id: other_user.id)
        end

        def follow!(other_user)
          following.create!(following_id: other_user.id)
        end

        def unfollow!(other_user)
           following.find_by(following_id: other_user.id).destroy
        end

        def self.search(search,word)
          if search == "forward_match"
            @user = User.where("name LIKE?","#{word}%")
          elsif search == "backward_match"
            @user = User.where("name LIKE?","%#{word}")
          elsif search == "perfect_match"
            @user = User.where("name LIKE?","#{word}")
          elsif search == "partial_match"
            @user = User.where("name LIKE?","%#{word}%")
          else
            @user = User.all
          end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     before_action :authenticate_user! ,   only: [:edit, :update, :index, :show]
     before_action :current_user,   only: [:edit, :update, :index, :show]
	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books
	end

	def index
		@users = User.all
		@user = current_user
		@book = Book.new
	end
	def edit
        @user = User.find(params[:id])
        if @user == current_user
            render "edit"
          else
            redirect_to user_path(current_user)
          end
    end
    def update
    	@user = User.find(params[:id])
    	if @user.update(user_params)
    	redirect_to user_path(@user.id),notice:"You have updated user successfully."
    else
    	render :edit
    end
    end

    def following
        @user = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end

    def followers
        @user = User.find(params[:id])
        @users = @user.followers
        render 'show_follower'
    end

    private 
    
    def user_params
    	params.require(:user).permit(:name, :profile_image, :introduction)
    end

end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
		user == current_user
	end

	def logged_in?
		!current_user.nil?
	end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.following.build) do |f| %>
  <%= f.hidden_field :following_id, value: @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
<div id="follow_form">
	<% if current_user.following?(user) %>
	<%= form_for(current_user.following_relationships.find_by(following_id:user.id),html: {method: :delete}) do |f| %>
<%= f.submit "unfollow", class: "btn btn-large follow-btn" %>
<% end %>
	<% else %>
	<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>
	<% end %>
</div>
<% end %>

app/views/users/_index.html.erb
<h2>Users</h2>
<% users.each do |user| %>
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th> </th>
		</tr>
	</thead>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: "no_image.jpg" ,size:'40x40'%></td>
			<td><%= user.name %></td>
    			</td>
			<td><%= link_to"Show",user_path(user.id) %></td>
		</tr>
<% end %>
</table>

app/views/users/_info.html.erb
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: "no_image.jpg" %>
  <table class="table">
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
         <th><%= link_to "フォロー(#{@user.followings.count})", following_user_path(@user), class: "nav-link" %></th>
      </tr>
      <tr>
         <th>followers</th>
          <th><%= link_to "フォロワー(#{@user.followers.count})", followers_user_path(@user), class: "nav-link" %></th>
      </tr>

    </table> 
    <% if user == current_user %>
    <%= link_to "", edit_user_path(current_user),class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
    <% else %>
    <%= link_to "", user_path,class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>

    <% end %>

    

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followings.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		  <strong id="followers" class="stat">
		  	<%= @user.followers.count %>
		  </strong>
		  followers
		</a>
	</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.following.find_by(following_id: @user.id),method: :delete) do |f| %>
  <%= f.hidden_field :following_id %>  
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@user) do |f| %>
    <div class="form-group has-icon">
        <label for="Name">Name</label>
        <%= f.text_field :name, autofocus: true %>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>
    <div class="form-group has-icon">
    <div class="user-edit-image">
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60%>
    </div>
    <label for="Image">Image</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
</div>
<label for="introduction">Introduction</label>
      <%= f.text_area :introduction %>
    <br><%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
<%= render 'users/info', user: @user %>
<%= render 'books/list', book: @book %>
</div>
<div class="col-xs-9">
<h2>Users</h2>
<% @users.each do |user| %>
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th> </th>
		</tr>
	</thead>
		<tr>
			<td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: "no_image.jpg" ,size:'40x40'%></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.followings.count %></td>
			<td>フォロワー数：<%= user.followers.count %></td>
			<td><% if current_user.following?(@user) %>
      			<%= render "unfollow", user: @user%>
    			<% else %>
     			<%= render "follow", user: @user %>
    			<% end %>
    			</td>
			<td><%= link_to"Show",user_path(user.id) %></td>
		</tr>
<% end %>
</table>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
<%= render 'users/info', user: @user %>
<% if logged_in? && @user != current_user%>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow", user: @user%>
    <% else %>
      <%= render "follow", user: @user %>
    <% end %>
  </div>
<% end %>
<%= render 'books/list', book: @book %>
</div>
<div class="col-xs-9">
<h2>Books</h2>

<table class="table table-hover table-inverse">
<thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
  </tr>
</thead>
<% @books.each do |book| %>

<tr>
  <td>
  	 <%= link_to user_path(@user) do %>
  	<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg'  ,fallback: "no_image.jpg" ,size:'40x40' %></td>
  	<% end %>
<td><%= link_to book.title,book_path(book.id) %></td>
<td><%= book.body %></td>
<td><%= book.book_comments.count %> コメント </td>

</tr>
<% end %>
</table>
</div>
</div>

app/views/users/show_follow.html.erb
<h3>Follow Users</h3>
<% if @users.empty? %>
ユーザーはいません
<% else %>
<% @user.followings.each do |user| %>
<table>
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th> </th>
		</tr>
	</thead>
	<tr>
		<td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: "no_image.jpg" ,size:'40x40'%></td>
	<td> <% user.name %></td>
	<td>フォロー数：<%= user.followings.count %></td>
	<td>フォロワー数：<%= user.followers.count %></td>
	<td><%= link_to '詳細',user_path(user)%></td>
</tr>
</table>
<% end %>
<% end %>

app/views/users/show_follower.html.erb
<h3>Follower Users</h3>
<% if @users.empty? %>
ユーザーはいません
<% else %>
<% @user.followers.each do |user| %>
<table>
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th> </th>
		</tr>
	</thead>
	<tr>
		<td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: "no_image.jpg" ,size:'40x40'%></td>
	<td> <% user.name %></td>
	<td>フォロー数：<%= user.followings.count %></td>
	<td>フォロワー数：<%= user.followers.count %></td>
	<td><%= link_to '詳細',user_path(user)%></td>
</tr>
</table>
<% end %>
<% end %>