config/routes.rb
Rails.application.routes.draw do

  root "home#top"
  
  get "home/about" =>"home#about"
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update, :index] do
  	member do
  		get :following, :followers
  	end
  end
  resources :relationships, only:[:create,:destroy]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only:[:create,:destroy]
 end
 get '/search' => 'search#search'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true,length: {maximum:200}
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def following?(other_user)
        following.find_by(following_id: other_user.id)
    end

    def follow!(other_user)
        following.create!(following_id: other_user.id)
    end

    def unfollow!(other_user)
        following.find_by(following_id: other_user.id).destroy
    end
def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where("title LIKE?","#{word}")
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@books = Book.all
		@book.user_id = current_user.id
		if @book.save
			redirect_to book_path(@book.id),notice:"You have creatad book successfully."
		else
			@books = Book.all
			render :index
		end
	end

	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end

	def show
		@books = Book.new
		@book = Book.find(params[:id])
		@user = @book.user
		@book_comment = BookComment.new
		@book_comments = @book.book_comments
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	def edit
			@user = current_user
			@book = Book.find(params[:id])
			if @book.user == current_user
            render "edit"
          else
            redirect_to books_path
          end
  	end

  	def update
		@book = Book.find(params[:id])
		@book.update(book_params)
	if	@book.update(book_params)
  		redirect_to book_path(@book.id),notice:"You have updated book successfully.."
  	else
    	render :edit
	end
	end

	def following
        @user = User.find(params[:id])
        @user = @user.followings
        render 'show_follow'
    end
    def followers
        @user = User.find(params[:id])
        @users = @user.followers
        render 'show_follower'
    end
    # def search
    # 	method = params[:search_method]
    # 	word = params[:search_word]
    # 	@books = Book.search(method,word)
    # end

private
    def book_params
        params.require(:book).permit(:title, :body, :user_id)
    end
    def user_params
	params.require(:user).permit(:name, :profile_image, :introduction)
	end
	 def correct_user
    @book = Book.find(params[:id])
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
  </tr>
</thead>
<% books.each do |book| %>
<tr>
  <td>
    <%= link_to user_path(book.user.id)  do %>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: "no_image.jpg" ,size:'40x40' %>
      <% end %>
    </td>
<td><%= link_to book.title,book_path(book.id) %></td>
<td><%= book.body %></td>


<td>
 <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book),method: :delete do %>
              <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= book.favorites.count %>いいね
             <% end %>
            <% else %>
              <%= link_to book_favorites_path(book),method: :post do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
               <%= book.favorites.count %> いいね
              <% end %>
              <% end %>
            </td>
              <td>
             <%= book.book_comments.count %> コメント 
            
           </td>
         </tr>
         <% end %>
       </table>

app/views/books/_list.html.erb
<h2>New book</h2>

<%= form_for(book) do |f| %>
<label for="book_title">Title</label>
<%= f.text_field :title%>

<label for="book_body">Opinion</label>
<%= f.text_area :body%>
    
<%= f.submit "Create Book",class: 'btn btn-primary col-xs-12' %>
<% end %>

app/views/books/books.html.erb

 <h2>Books</h2>
<section class="book">
<table cellspacing="10">
	<thead>
	<tr>
		<th></th>
		<th>Title</th>
		<th>Opinion</th>
		<th colspan="3"></th>
	</tr>
	</thead>
<% @books.each do |book| %>
<tbody>
<tr>
<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img" %></td>
<td><%=book.title %></td>
<td><%=book.opinion %></td>

</tr>
</tbody>
<% end %>

</table>
 

app/views/books/detail.html.erb
<h2>Book detail</h2>
<table class="table">
	<tbody>
		<tr></tr>
		<tr>
			<td><%= @user.name %></td>
			<td><%= @book.title %><td>
			<td><%= @book.opinion %></td>
			<td><%= link_to"Edit",%></td>
			<td> <%= "Destroy",book_path(book.id),method: :delete,data:{confirm:"Are you sure?"} %>
		</td>
	</tr>
</tbody>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for(@book,url:"/books/#{@book.id}")do|f|%>
<div class="col-xs-12">
<label for="book_title">Title</label>
<%=f.text_field :title %>

</div>
<div class="field row">
	<label for="book_body">Opinion</label>
<%=f.text_area :body %>
</div>
<div class="actions row">
	<%=f.submit'Update Book',class: 'btn btn-primary col-xs-12%' %>
</div>
<% end %>

<%= link_to"Show",book_path(@book.id)%>
|
<%= link_to"Back",books_path %>

app/views/books/index.html.erb
<div class="row">
  <div class="col-xs-3">
    <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
        
<%= render 'users/info', user: current_user %>
<%= render 'books/list', book: Book.new %>
</div>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
  </tr>
</thead>
<% @books.each do |book| %>
<tr>
  <td>
    <%= link_to user_path(book.user.id)  do %>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: "no_image.jpg" ,size:'40x40' %>
      <% end %>
    </td>
<td><%= link_to book.title,book_path(book.id) %></td>
<td><%= book.body %></td>


<td>
 <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book),method: :delete do %>
              <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= book.favorites.count %>いいね
             <% end %>
            <% else %>
              <%= link_to book_favorites_path(book),method: :post do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
               <%= book.favorites.count %> いいね
              <% end %>
              <% end %>
            </td>
              <td>
             <%= book.book_comments.count %> コメント 
            
           </td>
         </tr>
         <% end %>
       </table>
     </div>
   </div>

app/views/books/show.html.erb
<p class="notice">
</p>
<div class="row">
  <div class="col-xs-3">
<%= render 'users/info', user: @book.user %>
<%= render 'books/list', book: Book.new %>
</div>
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="col-xs-9">
<h2>Book detail</h2>
<table class="table">
		<tr>
			<td>
				<%= link_to user_path(@user.id)  do %>
				<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: "no_image.jpg" ,size:'40x40' %>
				<br><%= @book.user.name %> </td>
				<% end %>
			<td><%= @book.title %></td>
			<td><%= @book.body %></td>
			<td>
				<% if @book.user == current_user %>
				<%= link_to"Edit",edit_book_path(@book.id),class: "btn-sm btn-success edit_book_30910" %>
					<% end %>
				</td>
			<td>
				<% if @book.user == current_user %>
				<%= link_to"Destroy",book_path(@book.id),method: :delete,data:{confirm:"本当に消しますか？"}, class: "btn-sm btn-danger destroy_book_30910" %>
					<% end %>
				</td>
				<td>
					<ul>
					<% if @book.favorited_by?(current_user) %>
						<li>
						<%= link_to book_favorites_path(@book),method: :delete do %>
						  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
						  <%= @book.favorites.count %>いいね
						  <% end %>
						</li>
						<% else %>
						<li>
							<%= link_to book_favorites_path(@book),method: :post do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
   						 <%= @book.favorites.count %> いいね
  						<% end %>
						</li>
						<% end %>
					</ul>
						
						</td>
						<td>
							<ul>
							<li>
								<i class="fa fa-comment"></i>
								<a href="#comments"><%= @book.book_comments.count %></a>
							</li>
						</ul>
						

						</td>

					</tr>
		</table>

		<table>
			コメント一覧
			<ol>
	<% @book.book_comments.each do |book_comment| %>
	<tr><li class="comment">
      <div class="comment-body bb">
        
          
        <div class="comment-text">
          <div class="comment-author clearfix">
            <a href="#" class="link-author"><%= book_comment.user.name %></a>
            <span class="comment-meta">
              <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </div>
          <div class="comment-entry"><%= book_comment.comment %></div>
          <% if book_comment.user == current_user%>
  <div>
    <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
  </div>
<% end %>
        </div>
      </div>
    </li>
  <% end %>

		</tr>
	</ol>
	
		<%= form_for [@book,@book_comment] do |f| %>
		<tr>
			
			 <%= f.text_area :comment, class: "form-control",placeholder: "コメントをここに" %>
		
	
		<%= f.submit "送信する" %>
	

		</tr>
		<% end %>
	
</table>
</div>


