config/routes.rb
Rails.application.routes.draw do

  root "home#top"
  
  get "home/about" =>"home#about"
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update, :index] do
  	member do
  		get :following, :followers
  	end
  end
  resources :relationships, only:[:create,:destroy]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only:[:create,:destroy]
 end
 get '/search' => 'search#search'
end

app/views/layouts/_notifications.html.erb
<% if notice %>
　　<p><%= notice %></p>
<% end %>
<% if alert %>
   <p><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="https://kit.fontawesome.com/547003d1bb.js" crossorigin="anonymous"></script>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <header class="navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navber-nav navber-left">
          <span class="header">Bookers</span>
        </nav>

    
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li>
        <%= link_to 'Home',user_path(current_user),
        class: 'glyphicon glyphicon-home home'  %>
      </li>
      <li>
        <%= link_to 'Users', users_path,
        class: 'glyphicon glyphicon-user users' %>
      </li>
       <li>
        <%= link_to 'Books', books_path,
        class: 'glyphicon glyphicon-book books' %>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete,class: 'glyphicon glyphicon-log-out logout' %>
      </li>

    <% else %>
      <li>
        <%= link_to 'Home',root_path,
        class: 'glyphicon glyphicon-home home' %>
      </li>
      <li>
        <%= link_to 'About',home_about_path,
        class: 'glyphicon glyphicon-link about' %>
      </li>
      <li>
        <%= link_to "sign up", new_user_registration_path,
        class: 'glyphicon glyphicon-edit sign_up' %>
      </li>
      <li>
        <%= link_to "login", new_user_session_path,
        class: 'glyphicon glyphicon-log-in sign_in' %>
      </li>
    <% end %>
  </ul>
</div>
</header>
<div class="container">
  <div class="body">
    <p class= "message"><%= render 'layouts/notifications' %>
    </p>
    <% if user_signed_in? %>
    <%= form_tag(search_path , method: :get) do %>
　　<%= select_tag 'range' ,options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']]) %>
<%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
<%= text_field_tag (:word) %>
<%= submit_tag "検索" %>
<% end %>
<% end %>

    <%= yield %>
  </div>
</div>
  </body>
</html>